### ISSUE TITLE
Enable Mixed Content Compatibility Mode to load non-https images/videos on https sites

### ISSUE THREAD

**Issue by carstenhag** [xtools-at/Android-PWA-Wrapper#1]
Hey, the wrapper seems pretty nice to use, but when loading my website with it an image didn't show because the WebView was set to enforce https strictly. Googling found me this answer and code which fixes the issue.

I've just thrown the entire codeblock into the `WebViewHelper()` and it works, but I'm not sure if you would rather have it elsewhere, for this reason I did not make a PR.

https://stackoverflow.com/questions/32155634/android-webview-not-loading-mixed-content

**Comment by xtools-at** [comment]
ok thx for the heads-up!
as I've been working with Service Worker API to make my PWA offline-capable, everything had to be https, so I didn't hit this.
I'll add a Boolean to the Constants to turn it on/off individually.

**Comment by xtools-at** [comment]
just to make sure, you've used this method, targeting api >= 21, right?
```
webView.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);
```
don't really want to use *MIXED_CONTENT_ALWAYS_ALLOW*, if it's not necessary.

**Comment by carstenhag** [comment]
Oh sorry, I thought that I had linked to the specific answer. I used the entire code block from

https://stackoverflow.com/a/41461894

**Comment by xtools-at** [comment]
hmmm I wonder if that's really necessary, I think it can be solved easier :)

**Comment by xtools-at** [comment]
fixed, please re-open if you experience any issues 👍
