### ISSUE TITLE
Webview is frozen after clicking on external URL and returning

### ISSUE THREAD

**Issue by newpen** [xtools-at/Android-PWA-Wrapper#11]
Webview is freezed after clicking on external URL and returned

**Comment by xtools-at** [comment]
Was able to reproduce, never noticed before. Will debug it once I have some spare time. Or do you maybe already have a fix?

**Comment by xtools-at** [comment]
[fixed](https://github.com/xtools-at/Android-PWA-Wrapper/commit/a1852fca82f9c5e49bc19c5b6bba1d7be31cba7a)
