### ISSUE TITLE
Android 9 Security threat

### ISSUE THREAD

**Issue by Muratoter** [xtools-at/Android-PWA-Wrapper#16]
Hi,
I am getting security error dialog. 
![Screenshot_20191007_181411_com mobixa mobixa](https://user-images.githubusercontent.com/7453897/66324792-c981b880-e92e-11e9-9888-17f9ff9a8dea.jpg)

How can I fix it?

**Comment by sancamac** [comment]
try setting 
_**android:usesCleartextTraffic="true"**_  attribute
on application tag in _**AndroidManifest.xml**_ file
