### ISSUE TITLE
Not working on phone with OS less than 7.0

### ISSUE THREAD

**Issue by Wharley01** [xtools-at/Android-PWA-Wrapper#4]

**Comment by xtools-at** [comment]
Cannot reproduce, have my app running successfully on Lollipop and above. Care to elaborate?

**Comment by Wharley01** [comment]
I bundled the app to apk, it worked on my android(7.0) but saying "app not installed" for lower version phones

**Comment by xtools-at** [comment]
Don't want to be mean, but do you have any experience in Android development? Did you adjust the app's build.gradle?

**Comment by Wharley01** [comment]
Obviously no, I am web developer trying to make use of your PWA wrapper, would be happy if this can be sorted out

**Comment by Wharley01** [comment]
And I just adjusted build.gradle, but since then gradle is not building
