### ISSUE TITLE
How to disable bottom progress bar for loading

### ISSUE THREAD

**Issue by pankajkherwal** [xtools-at/Android-PWA-Wrapper#7]
Whenever PWA loads any new URL, a green progress bar shows at bottom. I don't want this progress bar, is there any option to disable it.

Thank You.

**Comment by xtools-at** [comment]
There's no setting for it - best would be to open the project in Android Studio, then remove it from the view and remove the references in the code (Android Studio should highlight those nicely for you)

**Comment by pankajkherwal** [comment]
Thanks

**Comment by pankajkherwal** [comment]
Hello Martin,

can you please give Image Upload support for html5 input file ?

Thanks. Regards
