### ISSUE TITLE
choose file of angular is not working or uploading any attachment button is not working

### ISSUE THREAD

**Issue by Priyadarshini181096** [xtools-at/Android-PWA-Wrapper#8]
choose file of angular is not working or uploading any attachment button is not working

Angularcode:
  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12" *ngIf = "toggle">
                        <input type="file" class="form-control forminput" accept="image/*" capture="camera" required (change)="selectFileTwo($event)">
                       </div>
                       <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-12" *ngIf = "toggle">
                         <button [disabled]="!selectedFilesTwo"
                         (click)="uploadTwo()" type="submit" >
                           <strong>Upload</strong>
                         </button>
                       </div>

**Comment by xtools-at** [comment]
as I don't use Angular, could you do some research an Android WebView + Angular + File Upload issues? maybe there's just a setting we'd need to enable for the webview to allow this, but I don't know what's required

**Comment by xtools-at** [comment]
closing here for now, please reopen if you have new info for us
